//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISP919_Naliv_LoginReg.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int ID { get; set; }
        public string NameService { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Time { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
    }
}
